# Generated by Django 5.2.7 on 2026-01-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(blank=True, help_text='Selected letter for the game. Null means random.', max_length=1, null=True)),
                ('is_random_letter', models.BooleanField(default=True, help_text='If True, letter will be randomly selected when game starts.')),
                ('selected_types', models.JSONField(default=list, help_text='List of selected game types (keys from GAME_TYPE_CHOICES)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
