# Generated by Django 5.2.7 on 2026-01-20 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text="Dictionary mapping game type keys to player's answers")),
                ('points', models.IntegerField(default=0, help_text='Total points earned in this round')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_answers', to='api.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.roomplayer')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('game_session', 'player')},
            },
        ),
    ]
