# Generated by Django 5.2.7 on 2026-01-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='points_per_category',
            field=models.JSONField(default=dict, help_text='Dictionary mapping game type keys to points earned per category'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Letter Game Room', max_length=100),
        ),
    ]
