# Generated by Django 5.2.7 on 2026-01-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playeranswer_points_per_category_alter_room_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeranswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_round',
            field=models.IntegerField(default=1, help_text='Current round number'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether all rounds are completed'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='round_letters',
            field=models.JSONField(default=list, help_text='List of letters used for each round'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_rounds',
            field=models.IntegerField(default=1, help_text='Total number of rounds to play'),
        ),
        migrations.AddField(
            model_name='playeranswer',
            name='round_number',
            field=models.IntegerField(default=1, help_text='Round number this answer belongs to'),
        ),
        migrations.AlterUniqueTogether(
            name='playeranswer',
            unique_together={('game_session', 'player', 'round_number')},
        ),
    ]
