# Generated by Django 5.2.7 on 2026-01-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_playeranswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='round_advance_scheduled',
            field=models.BooleanField(default=False, help_text='Whether round advancement is already scheduled'),
        ),
    ]
