# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gamesession_round_advance_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='round_timer_seconds',
            field=models.IntegerField(default=60, help_text='Timer duration in seconds for each round'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='round_start_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the current round started', null=True),
        ),
    ]
